name: DockerFlow
on: 
    push: 
        branches: ["main" ,"develop"]
jobs:
    "check_environment":
        runs-on: ubuntu-latest
        steps:
            - name: ls
              run: pwd
            - name: docker_setup
              uses: docker/setup-docker-action@v4
            - name: check_docker
              run: "docker --version"  
    
